name: Run Django Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Check out your repository
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your project dependencies

    - name: Run tests
      run: |
        python manage.py test membership  # Replace with your test command

